/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectdemo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Hp
 */
public class OrderProductSupplier extends javax.swing.JFrame {

    /**
     * Creates new form OrderProductSupplier
     */
    public OrderProductSupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        search2 = new javax.swing.JTextField();
        search3 = new javax.swing.JTextField();
        Searchfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoOPS = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 102));
        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(176, 31, 176));
        jLabel3.setText("Information of Order,Products & Suppliers");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 670, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("OrderID   :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 90, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("SupplierID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 90, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 153));
        jLabel5.setText("ProductID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 80, 20));

        search2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.add(search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 160, -1));

        search3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.add(search3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 160, -1));

        Searchfield.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.add(Searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 160, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setText("Ok");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 255));

        InfoOPS.setBackground(new java.awt.Color(153, 204, 255));
        InfoOPS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "SupplierId", "SupplierName", "SupplierContact", "ProductName", "Quantity", "PaymentOfOrder"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(InfoOPS);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 720, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bck.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String SupplierId = Searchfield.getText();
           if(Searchfield.getText().isEmpty())
            {
        
                JOptionPane.showMessageDialog(null,"Field is empty!");      
            }
           else{
                
           String searchQuery = "SELECT SUPPLIER.SupplierId, SUPPLIER.SupplierName,SUPPLIER.SupplierContact , PRODUCT.ProductName,ORDERS.Quantity, SUPPLIER.PaymentOfOrder FROM PRODUCT INNER JOIN SUPPLIER ON PRODUCT.ProductId= SUPPLIER.ProductId INNER JOIN ORDERS ON PRODUCT.ProductId= ORDERS.ProductId WHERE SupplierId ='"+SupplierId+"'";
            try {
                    ConnectMSSQL conn  = new ConnectMSSQL();
                    Connection connection = conn.connectDB();
                    Statement st = connection.createStatement();
                    ResultSet rs = st.executeQuery(searchQuery);
                    InfoOPS.setModel(DbUtils.resultSetToTableModel(rs));
                    } catch (SQLException ex) {
                        Logger.getLogger(BillDetails.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String ProductId = search2.getText();
           if(search2.getText().isEmpty())
            {
        
                JOptionPane.showMessageDialog(null,"Field is empty!");      
            }
           else{
                
           String searchQuery = "SELECT SUPPLIER.SupplierId, SUPPLIER.SupplierName,SUPPLIER.SupplierContact , PRODUCT.ProductName,ORDERS.Quantity, SUPPLIER.PaymentOfOrder FROM PRODUCT INNER JOIN SUPPLIER ON PRODUCT.ProductId= SUPPLIER.ProductId INNER JOIN ORDERS ON PRODUCT.ProductId= ORDERS.ProductId WHERE PRODUCT.ProductId ='"+ProductId+"'";
            try {
                    ConnectMSSQL conn  = new ConnectMSSQL();
                    Connection connection = conn.connectDB();
                    Statement st = connection.createStatement();
                    ResultSet rs = st.executeQuery(searchQuery);
                    InfoOPS.setModel(DbUtils.resultSetToTableModel(rs));
                    } catch (SQLException ex) {
                        Logger.getLogger(BillDetails.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String OrderId = search3.getText();
           if(search3.getText().isEmpty())
            {
        
                JOptionPane.showMessageDialog(null,"Field is empty!");      
            }
           else{
                
           String searchQuery = "SELECT SUPPLIER.SupplierId, SUPPLIER.SupplierName,SUPPLIER.SupplierContact , PRODUCT.ProductName,ORDERS.Quantity, SUPPLIER.PaymentOfOrder FROM PRODUCT INNER JOIN SUPPLIER ON PRODUCT.ProductId= SUPPLIER.ProductId INNER JOIN ORDERS ON PRODUCT.ProductId= ORDERS.ProductId WHERE ORDERS.OrderId ='"+OrderId+"'";
            try {
                    ConnectMSSQL conn  = new ConnectMSSQL();
                    Connection connection = conn.connectDB();
                    Statement st = connection.createStatement();
                    ResultSet rs = st.executeQuery(searchQuery);
                    InfoOPS.setModel(DbUtils.resultSetToTableModel(rs));
                    } catch (SQLException ex) {
                        Logger.getLogger(BillDetails.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderProductSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderProductSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderProductSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderProductSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderProductSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable InfoOPS;
    private javax.swing.JTextField Searchfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search2;
    private javax.swing.JTextField search3;
    // End of variables declaration//GEN-END:variables
}
